### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by a-1an**
Added example use case of Lexical Richness 
part of issue #45

### CODE REVIEW

**Comment by a-1an** [comment]
Hi, if this is merged, I'll work on issue #43  for this citation too.

**Comment by LSYS** [comment]
@a-1an this is not your own use case? nor does the use case uses the `LexicalRichness` package

**Comment by a-1an** [comment]
> @a-1an this is not your own use case? nor does the use case uses the `LexicalRichness` package

sorry, its a use case of lexical richness in general. It talks about why you should check the lexical richness.

**Comment by LSYS** [comment]
@a-1an this is not what was mentioned in #45

**Pull request closed without merging**
